name: Node.js CI (Combined)

on:
  # Original triggers for push and pull requests
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Scheduled workflow for additional runs
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours (0 minute, every 6th hour, every day)

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm start
